import { chromium } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
const browser = await chromium.launch({channel: 'msedge', headless: true})
const page = await browser.newPage({viewport: {width: 1440, height: 1000}})
const errors = []
page.on('pageerror', error => errors.push(error.message))
page.on('response', response => {if(response.status() >= 400) errors.push(`${response.status()} ${response.url()}`)})
await page.goto(process.env.BOARD_URL || 'http://127.0.0.1:5175/')
await page.locator('.document-hit').first().waitFor()
await page.waitForTimeout(2500)
await mkdir('artifacts', {recursive:true})
await page.screenshot({path:'artifacts/board-desktop.png'})
await page.locator('.document-hit').first().click()
await page.getByRole('dialog').waitFor()
await page.keyboard.press('Escape')
await page.getByRole('button', {name:'Cargar documento', exact:true}).click()
await page.locator('[name="account"]').fill('Cuenta de prueba')
await page.locator('[name="title"]').fill('Documento de verificación')
await page.locator('[name="url"]').fill('https://docs.google.com/document/d/test')
await page.getByRole('button', {name:'Colocar en el tablero'}).click()
await page.getByRole('dialog').waitFor({state:'hidden'})
await page.reload()
await page.getByRole('button', {name:/Argentina: Cuenta de prueba/}).click()
if (await page.getByRole('link', {name:'Abrir en Google Docs'}).getAttribute('href') !== 'https://docs.google.com/document/d/test') throw Error('Document URL changed')
await page.getByRole('button', {name:'Eliminar', exact:true}).click()
if (await page.evaluate(() => JSON.parse(localStorage.getItem('voccare-documents-v2')).length) !== 0) throw Error('Delete failed')
await page.getByRole('button', {name:'Ver muestra visual'}).click()
await page.getByRole('button', {name:/Chile: Cuenta Aurora/}).waitFor()
await page.getByRole('button', {name:'Buscar documentos', exact:true}).click()
await page.getByRole('textbox', {name:'Buscar documentos o países'}).fill('Uruguay')
await page.getByRole('dialog').getByRole('button', {name:/Uruguay · Cuenta Aurora/}).click()
await page.getByRole('dialog').waitFor()
await page.keyboard.press('Escape')
if (await page.locator('h1, nav, .app-header').count()) throw Error('Application chrome remains')
const fullViewport = await page.locator('.board-canvas').boundingBox()
if (fullViewport.width !== 1440 || fullViewport.height !== 1000 || fullViewport.x !== 0 || fullViewport.y !== 0) throw Error('Board does not fill viewport')
await page.mouse.wheel(0, 700)
if (await page.evaluate(() => scrollY !== 0 || document.documentElement.scrollHeight > innerHeight)) throw Error('Desktop scroll')
await page.setViewportSize({width:390,height:844})
await page.waitForTimeout(2000)
await page.screenshot({path:'artifacts/board-mobile.png'})
await page.getByRole('button', {name:'Países siguientes'}).click()
await page.getByRole('button', {name:/Bolivia: Cuenta Aurora/}).waitFor()
await page.getByRole('button', {name:'Cargar documento',exact:true}).click()
await page.getByRole('dialog').waitFor()
await page.keyboard.press('Escape')
if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth || document.documentElement.scrollHeight > innerHeight)) throw Error('Mobile overflow')
console.log(JSON.stringify({errors, checks:['render', 'open and Escape', 'create', 'persist', 'link', 'delete', 'all countries', 'search', 'full viewport', 'no navbar or scroll', 'mobile navigation']}, null, 2))
await browser.close()
if(errors.length) process.exitCode = 1
